### PR TITLE
add roles to records

### PR DESCRIPTION
**Pull request by matthiaseigner**
…tions for getting roles from multipie backend

### CODE REVIEW

**Comment by eiabea** [comment]
Could you please add an `How to set/migrate to roles`?

I am a bit lost getting the review started

**Comment by eiabea** [comment]
`requiresRoles` is set in 2 locations:
- `.gittt.yml`
- config file in `~/.gittt-cli/projects/xxx.json`

Updating the `.gittt.yml` does not update the project json file

**Comment by eiabea** [comment]
This might not be part of this PR, but i'd love to set a default role per project. The `.gittt.yml` is not the right place to save this, because this file gets committed to git, but maybe the `config.json` is suitable, with some kind of array/hashmap

**Comment by matthiaseigner** [comment]
> Could you please add an `How to set/migrate to roles`?
> 
> I am a bit lost getting the review started

Where would be the place for that? Just in the description of the pull request?

**Comment by matthiaseigner** [comment]
> `requiresRoles` is set in 2 locations:
> 
> * `.gittt.yml`
> * config file in `~/.gittt-cli/projects/xxx.json`
> 
> Updating the `.gittt.yml` does not update the project json file

Should this be the case? You would like to update the the config file from the gittt.yml? When would be the right place for that? At each call? Should the user be asked?

**Comment by eiabea** [comment]
It is currently possible to use any string as a `role`, at least with the `commit` action with the `-r` parameter. Should this string be validated?

image

**Pull request merged**
